import {StyleSheet} from "react-native";
import { Colors } from '@/constants/Colors';

export default (width: number) => StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "#00000066",
  },
  indicator: {
    width: 48,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#2b2b2b",
    alignSelf: "center",
    marginBottom: 8,
    marginTop: 10,
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  container: {
    height: "90%",
    backgroundColor: "#111113",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    overflow: "hidden",
    paddingBottom: 32,
  },
  sheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    marginBottom: 8,
  },
  backBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  backIcon: { color: "#f7b85a", fontSize: 24 },
  headerTitle: { color: Colors.secondary, fontWeight: "600", fontSize: 16 },
  headerLine: {
    borderBottomColor: "#2a2a2e",
    borderBottomWidth: 1,
    marginVertical: 12,
  },
  content: { paddingHorizontal: 24, paddingBottom: 140 },
  weekNav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  weekNavRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
  },
  navArrow: { color: Colors.secondary, fontSize: 28, paddingHorizontal: 8 },
  weekRange: { color: Colors.secondary, fontSize: 16, fontWeight: "600" },
  weekRow: { marginBottom: 20 },
  weekdayLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  weekdayLabel: { color: "#9b9b9b", width: 32, textAlign: "center" },
  dayNumbers: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 10,
  },
  dayButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  dayButtonSelected: {
    backgroundColor: "#f7b85a",
  },
  dayNumber: { color: "#f1f1f1", fontWeight: "600" },
  dayNumberSelected: { color: "#111" },
  sectionTitle: { color: Colors.secondary, fontSize: 16, marginBottom: 12 },
  blocksList: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  blockRow: {
    width: (width - 72) / 2,
    position: "relative",
  },
  blockSelect: {
    borderColor: "#2f2f33",
    borderWidth: 1,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#16161a",
  },
  blockSelectActive: {
    borderColor: "#f7b85a",
  },
  blockTime: {
    color: Colors.secondary,
    fontSize: 16,
    fontWeight: "600",
  },
  dropdownWrapper: {
    position: "absolute",
    top: 64,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  dropdown: {
    maxHeight: 220,
    borderRadius: 16,
    borderColor: "#2f2f33",
    borderWidth: 1,
    backgroundColor: "#16161a",
  },
  dropdownContent: {
    padding: 12,
    gap: 8,
  },
  dropdownItem: {
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#1f1f24",
    alignItems: "center",
    borderColor: "#1f1f24",
    borderWidth: 1,
  },
  dropdownItemActive: {
    borderColor: "#f7b85a",
    backgroundColor: "#2b2518",
  },
  dropdownItemText: { color: "#d6d6d9", fontSize: 16, fontWeight: "600" },
  dropdownItemTextActive: { color: "#f7b85a" },
  addBtn: {
    marginTop: 16,
    alignSelf: "center",
    padding: 8,
  },
  addPlus: { color: Colors.secondary, fontSize: 20 },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 16,
    right: 16,
  },
  saveBtn: {
    backgroundColor: "#f7b85a",
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: "center",
  },
  saveText: { color: "#111", fontWeight: "700", fontSize: 16 },
});